version: "3.9"
services:
  dev:
    build:
      context: .
    volumes:
      - .:/home/graphs_from_scratch/workspace
      - ~/.gitconfig:/home/graphs_from_scratch/workspace/.gitconfig
    ipc: host
    runtime: nvidia
    command: bash
    stdin_open: true
    tty: true
